# canonical test script; should probably be renamed
# along with references in .travis.yml
set -o nounset
set -o pipefail
set -o errexit

echo "Test shells:"
type ash bash dash mksh zsh || true
file $(type -p bash)

test/spec.sh oil-array -v
test/spec.sh oil-assign -v
test/spec.sh oil-bin -v
test/spec.sh oil-blocks -v
test/spec.sh oil-builtin-funcs -v
test/spec.sh oil-builtins -v
test/spec.sh oil-demo -v
test/spec.sh oil-expr-sub -v
test/spec.sh oil-expr -v
test/spec.sh oil-func-proc -v
test/spec.sh oil-interactive -v
test/spec.sh oil-json -v
test/spec.sh oil-keywords -v
test/spec.sh oil-regex -v
test/spec.sh oil-slice-range -v
test/spec.sh oil-tuple -v
test/spec.sh alias -v
test/spec.sh append -v
test/spec.sh arith-context -v
test/spec.sh arith -v
test/spec.sh array-compat -v
test/spec.sh array -v
test/spec.sh assign-deferred -v
test/spec.sh assign-dialects -v
test/spec.sh assign-extended -v
test/spec.sh assign -v
test/spec.sh assoc-zsh -v
test/spec.sh assoc -v
test/spec.sh background -v
test/spec.sh blog1 -v
test/spec.sh blog2 -v
test/spec.sh brace-expansion -v
test/spec.sh bugs -v
test/spec.sh builtin-bash -v
test/spec.sh builtin-bracket -v
test/spec.sh builtin-completion -v
test/spec.sh builtin-dirs -v
test/spec.sh builtin-eval-source -v
test/spec.sh builtin-getopts -v
test/spec.sh builtin-io -v
test/spec.sh builtin-printf -v
test/spec.sh builtin-special -v
test/spec.sh builtin-times -v
test/spec.sh builtin-trap -v
test/spec.sh builtin-vars -v
test/spec.sh builtins -v
test/spec.sh builtins2 -v
test/spec.sh case_ -v
test/spec.sh command-parsing -v
test/spec.sh command-sub -v
test/spec.sh command_ -v
test/spec.sh comments -v
test/spec.sh dbracket -v
test/spec.sh dparen -v
test/spec.sh empty-bodies -v
test/spec.sh errexit-oil -v
test/spec.sh errexit -v
test/spec.sh exit-status -v
test/spec.sh explore-parsing -v
test/spec.sh extglob-match -v
test/spec.sh for-expr -v
test/spec.sh func-parsing -v
test/spec.sh glob -v
test/spec.sh here-doc -v
test/spec.sh if_ -v
test/spec.sh interactive -v
test/spec.sh introspect -v
test/spec.sh let -v
test/spec.sh loop -v
test/spec.sh nameref -v
test/spec.sh osh-only -v
test/spec.sh parse-errors -v
test/spec.sh pipeline -v
test/spec.sh posix -v
test/spec.sh process-sub -v
test/spec.sh prompt -v
test/spec.sh quote -v
test/spec.sh redirect -v
test/spec.sh regex -v
test/spec.sh sh-func -v
test/spec.sh sh-options -v
test/spec.sh sh-usage -v
test/spec.sh smoke -v
test/spec.sh special-vars -v
test/spec.sh strict-options -v
test/spec.sh subshell -v
test/spec.sh tilde -v
test/spec.sh type-compat -v
test/spec.sh var-num -v
test/spec.sh var-op-bash -v
test/spec.sh var-op-len -v
test/spec.sh var-op-other -v
test/spec.sh var-op-patsub -v
test/spec.sh var-op-strip -v
test/spec.sh var-op-test -v
test/spec.sh var-ref -v
test/spec.sh var-sub-quote -v
test/spec.sh var-sub -v
test/spec.sh word-eval -v
test/spec.sh word-split -v
test/spec.sh xtrace -v
