name: "Test"
on:
  pull_request:
  push:
  schedule:
    # every sunday morning
    - cron: "0 0 * * 0"
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: services/toil-worker.sh run-dev-all-nix
  # temporary job to collect more information on assessment overhead?
  macos_perf_test:
    runs-on: macos-latest
    steps:
    - name: Disable syspolicy assessments
      run: |
        spctl --status
        sudo spctl --master-disable
        spctl --status || true
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: services/toil-worker.sh run-dev-all-nix
